# spec file for package bcfg2
#
# This file and all modifications and additions to the pristine
# package are under the same license as the package itself.
#
# This spec file was automatically generated by roboporter using:
#     bcfg2-0.9.5.7.tar.gz
#
# If you would like to take ownership of this package, and someone
# else has not done so already, then this package is available.
#
# Feel free to use, modify or replace this spec file as you see fit.
#
# Please follow the appropriate sw-porters contributing processes
# to sign up for, and enhance this package. For details see:
#    http://opensolaris.org/os/community/sw-porters/contributing/
#
# Gilles Dauphin 2010/05/31
# spec file comme from jucr,
# I try to bump to last releasee 1.0.1

%include Solaris.inc

%define mod_name bcfg2
%define mod_version 1.0.1
%define mod_namever bcfg2-1.0.1
%define mod_projdir bcfg2-1.0.1

# elementtree is included in python 2.5 and later 
%define python_version  2.6


Name:            SFEbcfg2
Summary:         Bcfg2 helps system administrators produce a consistent, reproduc
Version:         1.0.1
Source:          ftp://ftp.mcs.anl.gov/pub/bcfg/bcfg2-1.0.1.tar.gz
License:         Other
Url:             http://trac.mcs.anl.gov/projects/bcfg2
Distribution:    OpenSolaris
Vendor:          OpenSolaris Community


# OpenSolaris IPS Package Manifest Fields
Meta(info.upstream): http://trac.mcs.anl.gov/projects/bcfg2/wiki/MailingList
Meta(info.maintainer): ROBOPORTER <sw-porters-discuss@opensolaris.org>
Meta(info.repository_url): ftp://ftp.mcs.anl.gov/pub/bcfg/archive/bcfg2-1.0.1.tar.gz
Meta(info.classification): org.opensolaris.category.2008:Applications/System Utilities


BuildRoot:       %{_tmppath}/%{mod_namever}-build
SUNW_BaseDir:    %{_basedir}
SUNW_Copyright:  bcfg2.copyright
Requires:	runtime/python-26
Requires: 	library/python-2/python-extra-26
Requires:	file-monitor/gamin
Requires:	bash
Requires:	python-2/lxml-26
Requires:	python-2/pyopenssl-26
Requires:	python-2/python-twisted-26
Requires:	python-2/python-zope-interface-26
Requires:	python-2/simplejson-devel-26
Requires:	library/libxml2
Requires:	SUNWpython-cherrypy
Requires:	library/python-2/python-imaging-26
Requires:	library/python-2/ply
Requires:	python-2/python-gnome-libs-26
Requires:	library/mozilla-nss
Requires:	python-2/python-gst-26
Requires:	library/math

Requires:	ipkg
Requires:	libsasl
Requires:	ips/ips-incorporation

%description
Bcfg2 helps system administrators produce a consistent, reproduc

%prep


%setup -q -c -n  %{mod_namever}


%build


cd %{mod_projdir}
python ./setup.py build 


%install


rm -rf $RPM_BUILD_ROOT
cd %{mod_projdir}
python ./setup.py install --root=$RPM_BUILD_ROOT --prefix=%{_prefix} \
        --no-compile

# move to vendor-packages
if [ -d $RPM_BUILD_ROOT%{_libdir}/python%{python_version}/site-packages ] ; then  mkdir -p $RPM_BUILD_ROOT%{_libdir}/python%{python_version}/vendor-packages
  mv $RPM_BUILD_ROOT%{_libdir}/python%{python_version}/site-packages/* \
   $RPM_BUILD_ROOT%{_libdir}/python%{python_version}/vendor-packages/
  rmdir $RPM_BUILD_ROOT%{_libdir}/python%{python_version}/site-packages
fi




%files
%defattr (-, root, bin)
%dir %attr(0755, root, bin) %{_bindir}
%dir %attr(0755, root, bin) %{_libdir}
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/hostbase
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/templatetags
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration
%dir %attr(0755, root, bin) %{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils
%dir %attr(0755, root, bin) %{_datadir}
%dir %attr(0755, root, bin) %{_datadir}/bcfg2
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Hostbase
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Hostbase/repo
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Hostbase/templates
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Reports
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Reports/templates
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Reports/templates/clients
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Reports/templates/config_items
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/Reports/templates/displays
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/schemas
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/xsl-transforms
%dir %attr(0755, root, bin) %{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes
%dir %attr(0755, root, bin) %{_datadir}/man
%dir %attr(0755, root, bin) %{_datadir}/man/man1
%dir %attr(0755, root, bin) %{_datadir}/man/man5
%dir %attr(0755, root, bin) %{_datadir}/man/man8
%{_bindir}/bcfg2
%{_bindir}/bcfg2-admin
%{_bindir}/bcfg2-build-reports
%{_bindir}/bcfg2-info
%{_bindir}/bcfg2-ping-sweep
%{_bindir}/bcfg2-query
%{_bindir}/bcfg2-remote
%{_bindir}/bcfg2-repo-validate
%{_bindir}/bcfg2-server
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Frame.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Proxy.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/APT.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Action.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Blast.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Chkconfig.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/DebInit.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Encap.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/FreeBSDPackage.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/POSIX.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Portage.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/PostInstall.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/RPM.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/RPMng.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/RcUpdate.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/SMF.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/SYSV.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/YUMng.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/Yum.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/launchd.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/Tools/rpmtools.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/XML.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Client/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Component.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Logging.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Options.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Core.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/backends.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/hostbase/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/hostbase/models.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/hostbase/views.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/ldapauth.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/manage.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/nisauth.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/regex.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/settings.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Hostbase/urls.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugin.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Account.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Base.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Bundler.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Cfg.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Deps.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Hostbase.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Metadata.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Pkgmgr.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Rules.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/SGenshi.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/SSHbase.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Svcmgr.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/TCheetah.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/TGenshi.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/Vhost.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Plugins/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/backends.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/importscript.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/manage.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/nisauth.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/models.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/templatetags/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/templatetags/django_templating_sigh.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/templatetags/syntax_coloring.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/reports/views.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/settings.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Reports/urls.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/Statistics.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/Server/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/BaseDB.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/Checker.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/FileObject.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/HandshakeSettings.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/Session.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/SessionCache.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/SharedKeyDB.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/TLSConnection.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/TLSRecordLayer.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/VerifierDB.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/X509.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/X509CertChain.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/api.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/constants.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/errors.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/AsyncStateMachine.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/ClientHelper.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/HTTPTLSConnection.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/IMAP4_TLS.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/IntegrationHelper.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/POP3_TLS.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/SMTP_TLS.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/TLSAsyncDispatcherMixIn.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/TLSSocketServerMixIn.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/TLSTwistedProtocolWrapper.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/XMLRPCTransport.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/integration/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/mathtls.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/messages.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/AES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/ASN1Parser.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Cryptlib_AES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Cryptlib_RC4.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Cryptlib_TripleDES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/OpenSSL_AES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/OpenSSL_RC4.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/OpenSSL_RSAKey.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/OpenSSL_TripleDES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/PyCrypto_AES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/PyCrypto_RC4.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/PyCrypto_RSAKey.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/PyCrypto_TripleDES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Python_AES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Python_RC4.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/Python_RSAKey.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/RC4.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/RSAKey.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/TripleDES.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/__init__.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/cipherfactory.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/codec.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/compat.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/cryptomath.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/dateFuncs.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/hmac.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/jython_compat.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/keyfactory.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/prngd.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/rijndael.py
%{_libdir}/python%{python_version}/vendor-packages/Bcfg2/tlslite/utils/xmltools.py
%{_datadir}/bcfg2/Hostbase/repo/batchadd.tmpl
%{_datadir}/bcfg2/Hostbase/repo/dhcpd.conf.head
%{_datadir}/bcfg2/Hostbase/repo/dhcpd.tmpl
%{_datadir}/bcfg2/Hostbase/repo/hosts.tmpl
%{_datadir}/bcfg2/Hostbase/repo/hostsappend.tmpl
%{_datadir}/bcfg2/Hostbase/repo/named.tmpl
%{_datadir}/bcfg2/Hostbase/repo/namedviews.tmpl
%{_datadir}/bcfg2/Hostbase/repo/reverseappend.tmpl
%{_datadir}/bcfg2/Hostbase/repo/reversesoa.tmpl
%{_datadir}/bcfg2/Hostbase/repo/zone.tmpl
%{_datadir}/bcfg2/Hostbase/templates/base.html
%{_datadir}/bcfg2/Hostbase/templates/confirm.html
%{_datadir}/bcfg2/Hostbase/templates/copy.html
%{_datadir}/bcfg2/Hostbase/templates/dns.html
%{_datadir}/bcfg2/Hostbase/templates/dnsedit.html
%{_datadir}/bcfg2/Hostbase/templates/edit.html
%{_datadir}/bcfg2/Hostbase/templates/errors.html
%{_datadir}/bcfg2/Hostbase/templates/host.html
%{_datadir}/bcfg2/Hostbase/templates/index.html
%{_datadir}/bcfg2/Hostbase/templates/login.html
%{_datadir}/bcfg2/Hostbase/templates/logout
%{_datadir}/bcfg2/Hostbase/templates/logout.html
%{_datadir}/bcfg2/Hostbase/templates/logviewer.html
%{_datadir}/bcfg2/Hostbase/templates/navbar
%{_datadir}/bcfg2/Hostbase/templates/new.html
%{_datadir}/bcfg2/Hostbase/templates/remove.html
%{_datadir}/bcfg2/Hostbase/templates/results.html
%{_datadir}/bcfg2/Hostbase/templates/search.html
%{_datadir}/bcfg2/Hostbase/templates/zoneedit.html
%{_datadir}/bcfg2/Hostbase/templates/zonenew.html
%{_datadir}/bcfg2/Hostbase/templates/zones.html
%{_datadir}/bcfg2/Hostbase/templates/zoneview.html
%{_datadir}/bcfg2/Reports/templates/base.html
%{_datadir}/bcfg2/Reports/templates/clients/client-nodebox.html
%{_datadir}/bcfg2/Reports/templates/clients/detail.html
%{_datadir}/bcfg2/Reports/templates/clients/index.html
%{_datadir}/bcfg2/Reports/templates/clients/manage.html
%{_datadir}/bcfg2/Reports/templates/config_items/index.html
%{_datadir}/bcfg2/Reports/templates/config_items/listing.html
%{_datadir}/bcfg2/Reports/templates/displays/index.html
%{_datadir}/bcfg2/Reports/templates/displays/summary-block-direct-links.html
%{_datadir}/bcfg2/Reports/templates/displays/summary-block.html
%{_datadir}/bcfg2/Reports/templates/displays/summary.html
%{_datadir}/bcfg2/Reports/templates/displays/sys_view.html
%{_datadir}/bcfg2/Reports/templates/displays/timing.html
%{_datadir}/bcfg2/Reports/templates/index.html
%{_datadir}/bcfg2/schemas/atom.xsd
%{_datadir}/bcfg2/schemas/base.xsd
%{_datadir}/bcfg2/schemas/bundle.xsd
%{_datadir}/bcfg2/schemas/clients.xsd
%{_datadir}/bcfg2/schemas/deps.xsd
%{_datadir}/bcfg2/schemas/info.xsd
%{_datadir}/bcfg2/schemas/metadata.xsd
%{_datadir}/bcfg2/schemas/pkglist.xsd
%{_datadir}/bcfg2/schemas/report-configuration.xsd
%{_datadir}/bcfg2/schemas/rules.xsd
%{_datadir}/bcfg2/schemas/services.xsd
%{_datadir}/bcfg2/schemas/translation.xsd
%{_datadir}/bcfg2/schemas/types.xsd
%{_datadir}/bcfg2/schemas/xml.xsd
%{_datadir}/bcfg2/xsl-transforms/nodes-digest-mail.xsl
%{_datadir}/bcfg2/xsl-transforms/nodes-digest-rss.xsl
%{_datadir}/bcfg2/xsl-transforms/nodes-digest-www.xsl
%{_datadir}/bcfg2/xsl-transforms/nodes-individual-mail.xsl
%{_datadir}/bcfg2/xsl-transforms/overview-matrix-www.xsl
%{_datadir}/bcfg2/xsl-transforms/overview-stats-mail.xsl
%{_datadir}/bcfg2/xsl-transforms/overview-stats-rss.xsl
%{_datadir}/bcfg2/xsl-transforms/overview-stats-www.xsl
%{_datadir}/bcfg2/xsl-transforms/timing-summary-www.xsl
%{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes/boxypastel-css.xsl
%{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes/html-templates.xsl
%{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes/main-js.xsl
%{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes/sorttable-js.xsl
%{_datadir}/bcfg2/xsl-transforms/xsl-transform-includes/text-templates.xsl
%{_datadir}/man/man1/bcfg2.1
%{_datadir}/man/man5/bcfg2.conf.5
%{_datadir}/man/man8/bcfg2-admin.8
%{_datadir}/man/man8/bcfg2-build-reports.8
%{_datadir}/man/man8/bcfg2-info.8
%{_datadir}/man/man8/bcfg2-query.8
%{_datadir}/man/man8/bcfg2-remote.8
%{_datadir}/man/man8/bcfg2-repo-validate.8
%{_datadir}/man/man8/bcfg2-server.8
%changelog
* May 2010 - Gilles Dauphin
- inital spec for SFE
- Initial spec machine generated by roboporter
-  on: Wed Feb 10 16:35:08 2010
